### ISSUE TITLE
onnx.Loop

### ISSUE THREAD

**Issue by renxida** [nod-ai/SHARK-ModelDev#332]
This contains some notes from @renxida on onnx.If

@PhaneeshB is currently working on onnx.Loop

Find the if in [retinanet_resnet50_fpn_vaiq_int8 model support](https://github.com/nod-ai/SHARK-TestSuite/issues/199#top)
#199

**Comment by stellaraccident** [comment]
(you'll need to extend the importer for this as it is a "special" op)

**Comment by renxida** [comment]
> (you'll need to extend the importer for this as it is a "special" op)

I suspected I'll need more infra for this. Have simple test case onnx, will meet with rob to figure this out.

**Comment by renxida** [comment]
```python
import onnx
import numpy as np

# Define the input condition
cond = np.array(True).astype(bool)

# Define the output tensors
then_out = onnx.helper.make_tensor_value_info(
    "then_out", onnx.TensorProto.FLOAT, [5]
)
else_out = onnx.helper.make_tensor_value_info(
    "else_out", onnx.TensorProto.FLOAT, [5]
)

# Define constant tensors x and y
x = np.array([1, 2, 3, 4, 5]).astype(np.float32)
y = np.array([5, 4, 3, 2, 1]).astype(np.float32)

# Create constant nodes for x and y
then_const_node = onnx.helper.make_node(
    "Constant",
    inputs=[],
    outputs=["then_out"],
    value=onnx.numpy_helper.from_array(x),
)

else_const_node = onnx.helper.make_node(
    "Constant",
    inputs=[],
    outputs=["else_out"],
    value=onnx.numpy_helper.from_array(y),
)

# Create the graph for the 'then' branch
then_body = onnx.helper.make_graph(
    [then_const_node], "then_body", [], [then_out]
)

# Create the graph for the 'else' branch
else_body = onnx.helper.make_graph(
    [else_const_node], "else_body", [], [else_out]
)

# Create If nodes for 'then' and 'else' branches
then_if_node = onnx.helper.make_node(
    "If",
    inputs=["cond"],
    outputs=["then_res"],
    then_branch=then_body,
    else_branch=None,
)

else_if_node = onnx.helper.make_node(
    "If",
    inputs=["cond"],
    outputs=["else_res"],
    then_branch=else_body,
    else_branch=None,
)

# Create the main graph
main_graph = onnx.GraphProto()
main_graph.node.extend([then_if_node, else_if_node])

# Define the expected output
res = x if cond else y

# Define the ONNX model with the main graph
model = onnx.helper.make_model(main_graph, producer_name="test_if", opset_imports=[onnx.helper.make_opsetid("", 11)])

# Save the ONNX model to a file
onnx.save(model, "conditional_example.onnx")
```

This script generates an example onnx for conditionals.

**Comment by renxida** [comment]
Deprioritizing this now.

**Comment by renxida** [comment]
Back on it.

**Comment by renxida** [comment]
Todo list for now:
- [ ] find the torch aten / prim ops and types for if op, loop op, and graph regions
- [ ] find todo items for extending the importer

**Comment by renxida** [comment]
Torch ops to translate to:
PrimLoopOp

PrimIfOp

Methods / types of interest:

mlir::Region

PrimIfOp::getThenRegion
PrimIfOp::getElseRegion
PrimIfOp::getSuccessorRegions

**Comment by renxida** [comment]
Regions.

We are doing ONNX lowering weird. Torch has a named op thing. we're not doing that. Onnx ops are all the same op, with an attribute specifying what name they are. Our class definitions are interfaces on the same datastructure to store stuff, and validate things.

Stella made onnx this way because we didn't want a new dialect.

The parameters and features normally break into a couple of things:
inputs
attributes
result types
regions (new!)

an op can have any number of regions, regions can have any number of blocks. originally regions are just lists of blocks. they are just a quirk of that operations.

Regions are new: we made them to represent related blocks.

This is a concept that exists when we have goto. A region is a bunch of blocks with gotos.

Block: basic blocks. single entry single exit

regions: collection of connected blocks

Regions are analogous to a function body. A procedure. An entry and a return value.
But: it can get wonky. Linalg generic is an op, parallel and reduction dimensions.
Linalg is kindda like map reduce with regions. One op with map reduce components.

Whole idea with regions: scf dialect. Eventually we go to SCF.
We can reason about conditions and elide things. If we have regions, it's much easier to elide.

Regions help with: common subexpression elimination or dead code elimination (CSE, DCE)

In regions: no special blocks. It's just a list of blocks.

We'll have to do block moving: take block and move to new parent.

**Comment by renxida** [comment]
Rob gave this reference for manipulating regions:

https://github.com/llvm/llvm-project/blob/main/mlir/lib/Conversion/TosaToSCF/TosaToSCF.cpp

Inline if case

Rewrite terminators: the region's parent defines the rules about what terminators the region has. E.g. "must have 1 terminator block that ends in a particular op. e.g. functions must end with return"

e.g. in SCF, 2 blocks for If / else. Has to "scf yield" at the end. What's getting returned is given in the yield.

e.g. in while, one of the blocks has to have a conditional, and the other block has to have a yield block.
the conditional block and a yield / body block.

before / after block for for style loops

do while: before block and after block.

scf while: yield op is both the conditional and the before block

**Comment by renxida** [comment]
onnx binder: `binder.op`

`binder.op->getRegions() ` for a regionrange

RegionRange.size()

**Comment by renxida** [comment]
Move the regions to torch, then translate the ops inside the regions.
yield

**Comment by renxida** [comment]
```
/home/azureuser/miniconda/lib/python3.11/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "/home/azureuser/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/extras/onnx_importer.py", line 291, in import_node
    input_values.append(self._nv_map[input_name])
                        ~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'cond'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/azureuser/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/tools/import_onnx/__main__.py", line 77, in <module>
    _cli_main()
  File "/home/azureuser/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/tools/import_onnx/__main__.py", line 73, in _cli_main
    sys.exit(main(parse_arguments()))
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azureuser/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/tools/import_onnx/__main__.py", line 37, in main
    imp.import_all()
  File "/home/azureuser/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/extras/onnx_importer.py", line 262, in import_all
    self.import_node(node)
  File "/home/azureuser/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/extras/onnx_importer.py", line 293, in import_node
    raise OnnxImportError(
torch_mlir.extras.onnx_importer.OnnxImportError: Non topologically produced ONNX node input 'cond': input: "cond"
output: "then_res"
op_type: "If"
attribute {
  name: "then_branch"
  type: GRAPH
  g {
    node {
      output: "then_out"
      op_type: "Constant"
      attribute {
        name: "value"
        type: TENSOR
        t {
          dims: 5
          data_type: 1
          raw_data: "\000\000\200?\000\000\000@\000\000@@\000\000\200@\000\000\240@"
        }
      }
    }
    name: "then_body"
    output {
      name: "then_out"
      type {
        tensor_type {
          elem_type: 1
          shape {
            dim {
              dim_value: 5
            }
          }
        }
      }
    }
  }
}
```

**Comment by renxida** [comment]
continuing here: https://github.com/llvm/torch-mlir/issues/3136

**Comment by AmosLewis** [comment]
https://github.com/llvm/torch-mlir/pull/2825

**Comment by PhaneeshB** [comment]
support - https://github.com/llvm/torch-mlir/pull/3408
Test - https://github.com/nod-ai/SHARK-TestSuite/pull/248

**Comment by AmosLewis** [comment]
loop failed again for dlrm pytorch model

**Comment by PhaneeshB** [comment]
https://github.com/llvm/torch-mlir/pull/3408

**Comment by pdhirajkumarprasad** [comment]
```mlir
module {
  func.func @tf2onnx(%arg0: !torch.vtensor<[?,?,?,3],ui8>, %arg33: !torch.vtensor<[],si64>, %arg32: !torch.vtensor<[],i1>, %arg31: !torch.vtensor<[],si32>, %arg41: !torch.vtensor<[4],si64>, %arg42: !torch.vtensor<[],i1>, %arg43: !torch.vtensor<[],si32>, %arg44: !torch.vtensor<[3,300,300],f32>, %arg45: !torch.vtensor<[3],si32>) -> (!torch.vtensor<[],si32>, !torch.vtensor<[?,3,300,300],f32>, !torch.vtensor<[?,3],si32>) attributes {torch.onnx_meta.ir_version = 7 : si64, torch.onnx_meta.opset_version = 17 : si64, torch.onnx_meta.producer_name = "onnx.quantize", torch.onnx_meta.producer_version = "0.1.0"} {
    %621:3 = torch.operator "onnx.Loop"(%arg33, %arg32, %arg31) : (!torch.vtensor<[],si64>, !torch.vtensor<[],i1>, !torch.vtensor<[],si32>) -> (!torch.vtensor<[],si32>, !torch.vtensor<[?,3,300,300],f32>, !torch.vtensor<[?,3],si32>) {
    ^bb0(%arg1: !torch.vtensor<[],si64>, %arg2: !torch.vtensor<[],i1>, %arg3: !torch.vtensor<[],si32>):
      torch.operator_terminator %arg42, %arg43, %arg44, %arg45 : !torch.vtensor<[],i1>, !torch.vtensor<[],si32>, !torch.vtensor<[3,300,300],f32>, !torch.vtensor<[3],si32>
    }
    return %621#0, %621#1, %621#2  : !torch.vtensor<[],si32>, !torch.vtensor<[?,3,300,300],f32>, !torch.vtensor<[?,3],si32>
  }
}
```

**Comment by pdhirajkumarprasad** [comment]
[ir.txt](https://github.com/user-attachments/files/17010238/ir.txt)

complete IR

**Comment by kumardeepakamd** [comment]
@PhaneeshB is innx.loop not done yet? Should this issue be closed?
